### PR TITLE
Switch to Go 1.12

### PR DESCRIPTION
**Pull request by tamalsaha**
Signed-off-by: Tamal Saha <tamal@appscode.com>

### CODE REVIEW

**Comment by tamalsaha** [comment]
Fixes https://github.com/GoogleCloudPlatform/govanityurls/issues/29

**Comment by philips** [comment]
This won't work because a `handlers` section is still required. See https://github.com/etcd-io/govanityurls/blob/master/app.yaml

**Comment by philips** [comment]
#34 is my suggested fix

**Comment by tamalsaha** [comment]
@philips , https://cloud.google.com/appengine/docs/standard/go/config/appref#example

```
Optional. A list of URL patterns and descriptions of how they should be handled. App Engine can handle URLs by executing application code, or by serving static files uploaded with the code, such as images, CSS, or JavaScript.
```

It is working without handlers section in our deployments currently.

**Pull request closed without merging**
